apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-messages
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fullstack-messages
  template:
    metadata:
      labels:
        app: fullstack-messages
    spec:
      containers:
        - name: fullstack-messages
          image: wiljam/fullstack-messages:latest
