apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-messages
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fullstack-messages
  template:
    metadata:
      labels:
        app: fullstack-messages
    spec:
      containers:
        - name: fullstack-messages
          image: wiljam/fullstack-messages:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/messages
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: wiljamniklas
